"""Rename column in questions table

Revision ID: 3633769dc197
Revises: 873a027e9942
Create Date: 2023-03-30 12:53:45.133036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3633769dc197'
down_revision = '873a027e9942'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_14_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_games_question_14_id_questions'), 'questions', ['question_14_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_question_14_id_questions'), type_='foreignkey')
        batch_op.drop_column('question_14_id')

    # ### end Alembic commands ###
