"""Creates player and game models

Revision ID: 873a027e9942
Revises: f18de082ac04
Create Date: 2023-03-29 14:05:03.240856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873a027e9942'
down_revision = 'f18de082ac04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('question_1_id', sa.Integer(), nullable=True),
    sa.Column('question_2_id', sa.Integer(), nullable=True),
    sa.Column('question_3_id', sa.Integer(), nullable=True),
    sa.Column('question_4_id', sa.Integer(), nullable=True),
    sa.Column('question_5_id', sa.Integer(), nullable=True),
    sa.Column('question_6_id', sa.Integer(), nullable=True),
    sa.Column('question_7_id', sa.Integer(), nullable=True),
    sa.Column('question_8_id', sa.Integer(), nullable=True),
    sa.Column('question_9_id', sa.Integer(), nullable=True),
    sa.Column('question_10_id', sa.Integer(), nullable=True),
    sa.Column('question_11_id', sa.Integer(), nullable=True),
    sa.Column('question_12_id', sa.Integer(), nullable=True),
    sa.Column('question_13_id', sa.Integer(), nullable=True),
    sa.Column('question_15_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_games_player_id_players')),
    sa.ForeignKeyConstraint(['question_10_id'], ['questions.id'], name=op.f('fk_games_question_10_id_questions')),
    sa.ForeignKeyConstraint(['question_11_id'], ['questions.id'], name=op.f('fk_games_question_11_id_questions')),
    sa.ForeignKeyConstraint(['question_12_id'], ['questions.id'], name=op.f('fk_games_question_12_id_questions')),
    sa.ForeignKeyConstraint(['question_13_id'], ['questions.id'], name=op.f('fk_games_question_13_id_questions')),
    sa.ForeignKeyConstraint(['question_15_id'], ['questions.id'], name=op.f('fk_games_question_15_id_questions')),
    sa.ForeignKeyConstraint(['question_1_id'], ['questions.id'], name=op.f('fk_games_question_1_id_questions')),
    sa.ForeignKeyConstraint(['question_2_id'], ['questions.id'], name=op.f('fk_games_question_2_id_questions')),
    sa.ForeignKeyConstraint(['question_3_id'], ['questions.id'], name=op.f('fk_games_question_3_id_questions')),
    sa.ForeignKeyConstraint(['question_4_id'], ['questions.id'], name=op.f('fk_games_question_4_id_questions')),
    sa.ForeignKeyConstraint(['question_5_id'], ['questions.id'], name=op.f('fk_games_question_5_id_questions')),
    sa.ForeignKeyConstraint(['question_6_id'], ['questions.id'], name=op.f('fk_games_question_6_id_questions')),
    sa.ForeignKeyConstraint(['question_7_id'], ['questions.id'], name=op.f('fk_games_question_7_id_questions')),
    sa.ForeignKeyConstraint(['question_8_id'], ['questions.id'], name=op.f('fk_games_question_8_id_questions')),
    sa.ForeignKeyConstraint(['question_9_id'], ['questions.id'], name=op.f('fk_games_question_9_id_questions')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    # ### end Alembic commands ###
